### ISSUE TITLE
Multi file selection

### ISSUE THREAD

**Issue by sporkd** [iwasrobbed/Rails3-S3-Uploader-Plupload#1]
Hi.  Thanks for the great examples.

I was wondering why the plupload version doesn't work even if I set multi_selection to true.  I see your fancy example supports it, so I'm wondering if there's some limitation related to plupload with s3.

Also, after your experience using both plupload and fancy upload, do you have any insight as to which is the better tool, drawbacks, etc.  I'm using jquery, so downloading mootoos will add some extra overhead.  But perhaps worth it based on what I am seeing here.

Thanks in advance,
Peter

**Comment by iwasrobbed** [comment]
Hi Peter,

Sorry for the delayed response, I have been on vacation.  

For the plupload example, I disabled multiple file selection via these lines of code in the `uploads_helper.rb` file:

``` ruby
    init : {
              FilesAdded: function(up, files) {
                plupload.each(files, function(file) {
                  if (up.files.length > 1) {
                    up.removeFile(file);
                  }
                });
              }
            },
    multi_selection: false,
```

If you remove that code from the `init` statement and set `multi_selection` to true, it should do the trick for you.  However, you will still need to generate the rest of the UI code for supporting multiple uploads.  I would recommend using pluploads jquery UI widget for that purpose or creating your own.

As far as my preference goes between the tools, I prefer plupload since it supports far more runtimes (flash, html5, silverlight, etc) and is also built upon jquery.  If you are using jquery and attempt to use mootools alongside it, you may run into conflicts between the two and you'd have to put jquery into no-conflict mode for that page to avoid those.  Additionally, I don't think FancyUpload is being actively worked on anymore so it is not guaranteed to work in the future.

Thanks,
Rob

**Comment by sporkd** [comment]
No worries Rob, I'm the one who's working over the holiday weekend ;)

At any rate, thanks for the response. I totally missed the `if (up.files.length > 1)` part.   Im still experimenting with a few different solutions here, but I will give this a try if I end up going down the PlupLoad road.  Hey, I made a rhyme!
