### ISSUE TITLE
Not working on Firefox 6

### ISSUE THREAD

**Issue by emostar** [iwasrobbed/Rails3-S3-Uploader-Plupload#4]
I get the following error when using Firefox 6:

```
"Error #2049"
"Security error."
```

**Comment by iwasrobbed** [comment]
Have you set up your `crossdomain.xml` file like it said in the README?  You typically only get a `Security Error` when S3 denies access (either for a cross domain request or you have too restrictive of a bucket policy on your S3 bucket).

> For Flash: Make sure a public readable crossdomain.xml exists in the root directory of the S3 bucket you specified in config/amazon_s3.yml, with the following content (once you get it working, you should limit access to your domain to be more secure). An example can be found here
> 
> For Silverlight: Make sure a public readable clientaccesspolicy.xml exists in the root directory of the S3 bucket you specified in config/amazon_s3.yml, with the following content (once you get it working, you should limit access to your domain to be more secure). An example can be found here

**Comment by emostar** [comment]
Yes, I did that and it works for me under Safari, but not under Firefox 6.

I was actually debugging why it stopped working for me after upgrading from Firefox 5 to Firefox 6 and found this repository, which makes it really easy to reproduce. But still have no idea why it only doesn't work under Firefox 6.

**Comment by iwasrobbed** [comment]
Have you tried using [WireShark](http://www.wireshark.org/download.html) to debug what message Amazon is sending back?  They always send back an XML response which can provide more insight into the issue.  Unfortunately Plupload is a black box and really difficult to debug since there is no verbose debugging mode.

I have some more info about using WireShark on the readme as well.  I just downloaded Firefox 6.0 and tried it on my bucket and it worked like normal for me.  I would look at using Firebug and WireShark to debug your specific issue since it could be that the crossdomain is not in the proper place or that the Amazon policy that you're generating in the Rails helper is not valid and the S3 server is rejecting it (which is sent back as an error via XML).

By the way, I'm using Mac OS X 10.6 but that shouldn't make a difference.

**Comment by emostar** [comment]
I found the problem!

Firefox 6 is forcing it to use HTTPS to upload for some reason. I had to modify the uploads_helper to set the url to `https://#{bucket}.s3.amazonaws.com/`

After that change it started working.

**Comment by iwasrobbed** [comment]
Glad you figured it out, thanks for updating with a solution :)  Best of luck to you, Jon!
