### ISSUE TITLE
Weird problem in nginx and unicorn production environment

### ISSUE THREAD

**Issue by ReLrO** [iwasrobbed/Rails3-S3-Uploader-Plupload#5]
Hey.

I've been using your great example successfully in my development environment and was able to upload large files to my S3 bucket. The problem occurred when I deployed project to my production server (nginx and unicorn). 
When trying to upload a file it hangs after uploading few percents. I tried checking for the error in Wireshark and got the following:

Http/1.1 400 bad request
Server: AmazonS3

Error: EntityTooLarge
Message: Your proposed upload exceeds the maximum allowed size
proposed size: 512743
MaxSizeAllowed: 512000

I only trying to upload a 5MB file. I can't find any reasonable explantation for why it is happening and I would very much appreciate your help. 

Thanks in advance,
Ariel.

**Comment by iwasrobbed** [comment]
Hi Ariel,

It's telling you that the maximum file size you are setting in the S3 policy is set to 512000 but you are uploading a file that is 512743.  S3 will reject any files that are larger than the maximum file size you specify in that signed policy.  This controls what size files S3 allows the user to upload (in case they bypass that setting in browser).

This gets set here:

https://github.com/iwasrobbed/Rails3-S3-Uploader-Plupload/blob/master/app/helpers/uploads_helper.rb#L32

and here:

https://github.com/iwasrobbed/Rails3-S3-Uploader-Plupload/blob/master/app/helpers/uploads_helper.rb#L45

Try setting it to a larger number (like `500.megabytes` in the example app) and see if it works.

**Comment by ReLrO** [comment]
I neglected to mention that I did set that value to 900.megabytes, so that's not the problem.
Also, this works perfectly in development environment. I can upload much larger files without any problems. 
This only happens after deployment. 

Thanks for your quick reply, BTW!

**Comment by ReLrO** [comment]
Hey Iwasrobbed, Do you have any other suggestion? 
I am really out of ideas...

**Comment by iwasrobbed** [comment]
You sure you don't have different options for development versus production?  If S3 is sending you back that XML error message with `MaxSizeAllowed: 512000`, then the Base64 encoded policy file you are sending to S3 before the file transfer _definitely_ has a 5mb limit set within it even though you think you're setting it to `900.megabytes`.  There's no other solution.  Try doing a `puts` of `options[:max_filesize]` in the production environment and see what it's getting set to.

Amazon has something like a 5 GB file limit so it shouldn't matter between dev / production environments unless your option variables are different between the two.  Please keep in mind that this size constraint is different than the one you set for the Flash uploader (which the user can possibly bypass) found here: https://github.com/iwasrobbed/Rails3-S3-Uploader-Plupload/blob/master/app/helpers/uploads_helper.rb#L69 ... So if by chance you're setting that one thinking it's the correct one, please go back and look at the prior lines of code I pointed to.

**Comment by ReLrO** [comment]
I cannot understand it either. That's why I am so frustrated :(
This is the gist of my configurations:
https://gist.github.com/2695764

I don't have any other configurations for a different environment. 
Am I missing something? Is there another place where this could be limited?

BTW, when running "rails s -e production" it works flawlessly. The problem only occurs after deploying to nginx

**Comment by iwasrobbed** [comment]
Are you passing that max filesize in as an option when you instantiate the uploader?

In Ruby, this line will _only_ set itself to `3000.megabytes` if the `options[:max_filesize]` object is nil: 

``` haml
options[:max_filesize] ||= 3000.megabytes
```

An example of you doing this would be writing this in your view file:

``` ruby
:plain      
    #{s3_uploader(:max_filesize => 5.megabytes)}
```

That would override the default you've set of `3000.megabytes` and instead set the max filesize allowed to `5.megabytes` which is why I was asking if you could debug what the `options[:max_filesize]` object was being set to in the production environment.

If it's something dealing with your nginx setup, I apologize but I won't be able to help you with that.  I really can't imagine it has something to do with that though.

**Comment by ReLrO** [comment]
yes, I am sending it also as a parameter:
  :plain
    #{s3_uploader(:max_filesize => 3000.megabytes)}

btw earlier it was 500mb not 3000.
now I received a different number in the error when using 3000:
proposed file size: 3073195
MaxSizeAllowed : 3072000

and I am still only trying to upload a 5mb file so I don't know how it came up with these numbers.

**Comment by iwasrobbed** [comment]
I'm not entirely sure either.  The sizes it is showing are actually closer to 3 megabytes rather than 3000.  You can type `3.megabytes` into the rails console to see what values it provides:

3 megabytes = 3145728 
3000 megabytes = 3145728000

Are you POSTing the upload through your nginx server or directly to S3?  If so, nginx might be restricting the upload size https://www.google.com/search?aq=1&oq=nginx+file+up&sourceid=chrome&ie=UTF-8&q=nginx+file+upload+limit

**Comment by iwasrobbed** [comment]
By the way, you still haven't told me what your server thinks `options[:max_filesize]` is in your production environment before it goes into the policy to be Base64 encoded.  You need to do a `puts` or `Rails.logger` output of that to the logs and let me know what it's set to before I can help you any more.

**Comment by ReLrO** [comment]
I am doing exactly what I pasted in the gist, so it should go straight to s3, no?
might it be possible that when writing 3000mb, I actually get 3mb? seems odd, since it doesn't happen in development.

**Comment by iwasrobbed** [comment]
Rails converts the `3000.megabytes` correctly to a value that Amazon understands, but we still don't know what that value is when it goes into your policy file since you haven't debugged the value for me yet.  According to your gist, you're posting to S3 so nginx shouldn't be the problem.

I would really recommend taking my example app and running it "as-is" on your nginx setup.  It's been verified to work on Heroku (which uses nginx).  So if the example app works on your nginx setup, then you have an issue with your current code.  If it doesn't work on your nginx code, then there is an issue with that nginx setup.

**Comment by ReLrO** [comment]
You were right!! Added the debugger line: got 3072000
How could that be? what am I missing?
How come that it is different in the dev environment? I get  3145728000 there

**Comment by iwasrobbed** [comment]
You must be setting it in the code somewhere.  Again, I emphasize starting with a basic example (that you know already works) like the one I created and then going from there.  If it works in production, there is an issue with your current code.  I am going to go ahead and close this issue since it should be easy enough for you to fix your code.

**Comment by ReLrO** [comment]
Ok, Thank you very much for your help!

**Comment by ReLrO** [comment]
Hey Rob. 
Thank you very much for your help yesterday. I was able to repair the size limit error but not the problem.
When I try to upload large files, it hangs after uploading some percents. 
I deployed your solution to heroku and tried to upload 200 mb file, the same thing happened. The file hangs in the middle. 
This time I don't see an error in Wireshark.
Any ideas?

**Comment by iwasrobbed** [comment]
Have you checked the browser console to see if it's returning any error messages via the Javascript callbacks?  Typically it will appear to be hanging if there is an issue with the internet connection.  You should be checking for this in the callbacks that Plupload provides (the example app just outputs a message to the browser console instead of showing an alert dialog).

To be honest, after a few months of using Plupload to upload videos and having issues with the upload failing, I ended up switching over to SWFUpload instead since sites like TwitVid use it with good success.  It only took me about half of a day to get it working.
